### ISSUE TITLE
Why subtract the last layer output with 0.5

### ISSUE THREAD

**Issue by JunwenBai** [hinanmu/C2AE_tensorflow#4]
I saw hidden2 = tf.subtract(hidden2, 0.5) in Fe as well as in Fx. May I ask why you need to subtract the last layer with 0.5?

**Comment by hinanmu** [comment]
The reason why I added this formula is because I saw this in the MATLAB code of the author of the paper. I am not sure why the author did this.

**Comment by hinanmu** [comment]
> I saw hidden2 = tf.subtract(hidden2, 0.5) in Fe as well as in Fx. May I ask why you need to subtract the last layer with 0.5?

The reason why I added this formula is because I saw this in the MATLAB code of the author of the paper. I am not sure why the author did this.

**Comment by chihkuanyeh** [comment]
Hi, I'm the author of the original paper, we subtract 0.5 to scale the output of Fe from -0.5 to 0.5. This makes sense since Fe is limited to be orthogonal, and thus should not scale from 0 to 1.
